apiVersion: v2
name: tellery
description: A Helm chart for Kubernetes
annotations:
  artifacthub.io/images: |
    - name: tellery
      image: tellery/tellery:0.4.0-beta
    - name: connector
      image: tellery/connector:0.4.0-beta
  artifacthub.io/prerelease: 'true'
  artifacthub.io/license: Apache-2.0 License
type: application
version: 0.0.1
appVersion: 0.4.0-beta
dependencies:
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 14.3.3
    condition: redis.enabled
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 10.4.8
    condition: postgresql.enabled
