remote: origin
target-branch: main
chart-dirs:
  - charts
chart-repos:
  - stable=https://charts.helm.sh/stable
helm-extra-args: --timeout=900s --set postgresql.enabled=true --set system.web.host=tellery.io
