name: "Sync README to gh-pages"

on:
  push:
    branches:
      - main
    paths:
      - "README.md"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (main)
        uses: actions/checkout@v2

      - name: Copy README.md to temp
        run: |
          cp -f README.md ${{ runner.temp }}/README.md
      - name: Checkout (gh-pages)
        uses: actions/checkout@v2
        with:
          ref: gh-pages

      - name: Git Push (gh-pages)
        run: |
          cp -f ${{ runner.temp }}/README.md .
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add README.md
          git commit --signoff -m "sync README.md from main branch"
          git push